### ISSUE TITLE
Compendium Folder Icons keep resetting

### ISSUE THREAD

**Issue by Elmaro** [earlSt1/vtt-compendium-folders#166]
Hi, so for some reason, my compendium folders keep resetting their images, and the image paths.
no matter what I change it to, the folders reset to this (first image)
![image](https://user-images.githubusercontent.com/29361562/189670245-43a3f5da-67b8-40c3-b799-1dcc6bb5a41d.png)

The image doesn't actually exist, and I don't know why it is selected. I started a new world, only enabled the compendium folder module and the issue still persists.
 If I click on the folder icon, change it and update it, the image will change. But if I refresh the page, the image always reverts to that. If I delete "fa-solid:folder" and save, it returns to the default image, but if I refresh the page, it returns to the "fa-solid:folder"

Do you have any advice on what is going on?

Here is a video showing you what happens when I click stuff
(With some smooth bossa nova to chill to as you watch)
https://i.gyazo.com/c24dd356fb3d8f6ff49b9d074f6d4871.mp4

And another video showing some more things
https://i.gyazo.com/e54df49c168de9a13bc02006ac5d3577.mp4

**Comment by earlSt1** [comment]
Hi, I've had this reported a few times and i'm working on figuring out whats causing it. Thanks for the videos+screenshots.

I'm assuming you are on V10?

**Comment by Elmaro** [comment]
Hi, and thank you for the quick reply!
Sorry, I should have mentioned, I am still on V9 right now. Will be for a
while until some of the modules I use upgrade.

If there is anything else you need from me please let me know,

**Comment by earlSt1** [comment]
Gotcha, I think i see what is happening, but i'm not sure how its happening as i cant replicate it locally. 

Do you think I could have access to your world so I can debug on there? You can ping me on discord with the details if thats ok (Erceron#0370)

**Comment by Hawkeye131** [comment]
I am having this same issue on V10 clicking refresh seems to fix it but on restart its back it seems to be only on the GM side though.  

I think this is the error 

![image](https://user-images.githubusercontent.com/51892511/192374610-4e657911-80c7-4524-abc7-0454f4028dbf.png)

**Comment by Elmaro** [comment]
Hi, I'm so sorry for being so long in replying to this.
I found out what the issue was. There are 2 modules that I installed that
caused this problem to appear. Even after uninstalling one of them the
problem continued to persist.

I am currently not with my computer so I am unable to check, but I will be
hopefully tomorrow. I can then tell you what they were and hopefully this
will help you in diagnosing the exact problem.

I did some troubleshooting and a lot of reinstalling blank systems to try
and localise the problem so hopefully when I let you know the names of the
modules, it will help

**Comment by iotech-fvtt** [comment]
@Elmaro What were the two modules you think are causing this?

**Comment by earlSt1** [comment]
@Elmaro Are you hosting on the Forge by chance? There has been an issue fixed recently on their end related with compendiums that has caused issues with CF

**Comment by Hawkeye131** [comment]
> 

This issue is on self hosted as well. IDK about forge.

**Comment by iotech-fvtt** [comment]
Self hosted here too. On world load, the custom icons I chose are showing
as broken image links. If I fix one of them, ALL of them are then correct
(they're all different but in the same folder). I note that when
theyre broken, the path in the Edit Folder dialog is the original path to
fa-folder, but it can't find it. Maybe it is resetting to the mod folder
rather than the User Data folder?

**Comment by earlSt1** [comment]
Well fa-folder implies that theres some CSS shenanigans about, since that is the fontawesome class that represents the default folder icon, except i cant find anything in my code that would set that. 

I have been looking into the issue but annoyingly its a real puzzler since i cant replicate it. Is someone else in this thread available to invite me to their game so I can debug there?

**Comment by Elmaro** [comment]
Hi, thank you for emailing me again to remind me, luckily I just got home
last night (UK time zone)

So, there were two modules involved in the issue - the first was
"Game-Icons.Net" by "thDM"
https://eu.forge-vtt.com/bazaar/package/game-icons-net (Forge Link)

This was the module that forced folder icons to be replaced with
"fa-folder" or whatever it was called.

And the second Module was Alpha Suite (
https://eu.forge-vtt.com/bazaar/package/alpha-suit)
Even with Game-Icons.net uninstalled, Alpha suite would continuously force
yout module to use "fa-" something

After removing both of those modules, and deleting their references, the
issue resolved itself

I hope this helps, let me know if you need any more information


All the very best


Lamarr

**Comment by earlSt1** [comment]
Fantastic!!! thats the module thats causing issues - Alpha suite.

I'll reach out to the module dev to see if i can resolve this. In the meantime you'll have to disable it.

**Comment by earlSt1** [comment]
Raised an issue here: https://github.com/averrin/alpha-suit/issues/2

**Comment by iotech-fvtt** [comment]
I bumped it over there, thanks! In the meantime, I disabled Alpha Suite (I still have Compendium Browser and it works fine). 
Thanks, @earlSt1

**Comment by earlSt1** [comment]
Looks like this is fixed in the latest update of Alpha Suite. Closing this for now

**Comment by Hawkeye131** [comment]
This seems to be still a bug on this end. Even with alpha suit totally removed the error is still happening.  

Confirmed it is happening even without anything else installed. @earlSt1

**Comment by earlSt1** [comment]
> This seems to be still a bug on this end. Even with alpha suit totally removed the error is still happening.
> 
> Confirmed it is happening even without anything else installed. @earlSt1

Hmm, have you tried with all modules off other than CF? and its still replacing the icons when you try to set them back to normal?

**Comment by Hawkeye131** [comment]
> Hmm, have you tried with all modules off other than CF? and its still replacing the icons when you try to set them back to normal?

Yes only using CF it still dose it

**Comment by earlSt1** [comment]
Can you send me an invite to your world so i can have a look? My discord is @Erceron#0370

**Comment by earlSt1** [comment]
For anyone else that has this issue that did have Alpha Suite installed when it was overwriting the folder icons, if you edit all folders with broken icons, delete the icon text field, and save, then it should be back to normal
