### ISSUE TITLE
Exporting data to compendium causes folder structure to not render in some cases

### ISSUE THREAD

**Issue by earlSt1** [earlSt1/vtt-compendium-folders#34]
Hi, not sure it's fixed. Whenever I try to export data to a compendium, I get this:
![image](https://user-images.githubusercontent.com/73638904/102382656-f6b60600-3fca-11eb-8c97-45f225b2b173.png)
with this error in the console:
![image](https://user-images.githubusercontent.com/73638904/102382726-0afa0300-3fcb-11eb-9214-cc3d7aeb91c8.png)
It was on a gm account.

Edit: Apparently it works with a brand new compendium without any entries in it, but it kinda defeats the purpose to me.

_Originally posted by @Honkou in https://github.com/earlSt1/vtt-compendium-folders/issues/32#issuecomment-746666919_

**Comment by earlSt1** [comment]
@Honkou can you let me know what happens when you import all content from that compention, create a new compendium, then export all that content into a new compendium? 

I had the issues you're describing with an old compendium of mine, but after deleting it all, exporting it into a new compendium, and exporting a new folder into it, I can't get it to error.

**Comment by Honkou** [comment]
So the only folder that remains looks like this:
![image](https://user-images.githubusercontent.com/73638904/102723226-ef626580-4306-11eb-93d0-ec8ebcacb7d8.png)
Everything else is just scattered.

When trying to import it, I get this error:
![image](https://user-images.githubusercontent.com/73638904/102723221-e5d8fd80-4306-11eb-99d7-837768f93723.png)

**Comment by Honkou** [comment]
The problem occurs only when trying to export data to a compendium that some data was already imported to.

**Comment by earlSt1** [comment]
Hmm ok, which version of foundry + system are you running? (it looks like 5e but just to be sure). 

Also if you've still got a copy of the faulty compendium can you attach the db file to this issue? (if it's a world compendium you can find it in `Data/worlds/<worldName>/packs`)

**Comment by earlSt1** [comment]
Alrighty I think I've fixed it. Can you try installing the following manifest and trying again?

https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/master/test/module.json

**Comment by Cussa** [comment]
Hello, I'm using the version 2.1.7 with Foundry 0.7.9 and the error is still happening.

**Comment by earlSt1** [comment]
Hi @Cussa, was the error appearing after you try to merge folders when exporting again? or was it just from opening the compendium?

**Comment by Cussa** [comment]
When I tried to "re"export the actors, to have it updated.

**Comment by earlSt1** [comment]
Ah ok, if you're still using a compendium that was affected by this bug (where the folders dont render right), then re-exporting wont fix it unfortunately. I can see about coming up with a macro to clean up the compendium so you can try again.

**Comment by Cussa** [comment]
The point is that I started to use it today, already on the version 2.1.7. I export the content to a Compendium. After I did more changes, I tried to export again to update the content, and it created the CF_tempEntry values.

**Comment by earlSt1** [comment]
I see ok, looks like there is another bug somewhere still causing this issue. I'll do some more digging later.

**Comment by earlSt1** [comment]
@Cussa and @Honkou if you're available to test can you try uninstalling an reinstalling using this manifest? In my test environment i was able to replicate your issue, and the latest changes in this test branch fixed it for me: https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/master/test/module.json

**Comment by Honkou** [comment]
Sorry for not responding earlier, holiday time got pretty crazy. 
Uninstalling and reinstalling with your latest change seems to have done the trick. Thank you for all the help!

**Comment by earlSt1** [comment]
No problem, and thats great to hear! Soon i'll push an update which you will be able to update from the test version through foundry

**Comment by Cussa** [comment]
Sorry for not responding earlier too. I'll do some tests tomorrow night and I will inform you the results.

**Comment by earlSt1** [comment]
Got someone else to test this too and they have reported the problem is now solved. Fix now implemented in v2.1.8 and will close this for now.
