### ISSUE TITLE
Feature Request: text colour

### ISSUE THREAD

**Issue by geoidesic** [earlSt1/vtt-compendium-folders#45]
Hi... love this module.
Would be great if you could also set the text colour. Currently it defaults to white, which isn't legible if you choose light colour folders.

**Comment by geoidesic** [comment]
I was looking at Scene folders, not compendium. Would be nice if one could set colours on compendium folders though.

**Comment by earlSt1** [comment]
Hi, so unfortunately naming can get confusing in this module. Folders For Compendiums (in the compendium sidebar directory) already have this functionality. I thought I added it to Folders In Compendiums too, however I cant remember. Which one are you talking about? :smile:

**Comment by earlSt1** [comment]
Hi again, sorry it's been a while,, but i've just pushed some changes to the testing branch that add text color options to folders in compendiums (as you can see from this *awfully garish image*).

![image](https://user-images.githubusercontent.com/13738280/113062904-616f0400-91ac-11eb-921e-d67ba7180af3.png)

Could you give it a test by uninstalling your current version and installing this one using the manifest link?

https://raw.githubusercontent.com/earlSt1/vtt-compendium-folders/master/test/module.json

I **strongly** recommend backing up any compendiums you will be using to test.

**Comment by geoidesic** [comment]
Works perfectly for compendiums!

**Comment by geoidesic** [comment]
Where I still have issues are on other folders e.g. attached
<img width="688" alt="Screenshot 2021-04-02 at 13 21 47" src="https://user-images.githubusercontent.com/4637995/113415148-81721380-93b6-11eb-89fd-8d80d452c105.png">
There's no option to control the text color for folders on any of the other tabs except for compendiums.

**Comment by geoidesic** [comment]
> Hi, so unfortunately naming can get confusing in this module. Folders For Compendiums (in the compendium sidebar directory) already have this functionality. I thought I added it to Folders In Compendiums too, however I cant remember. Which one are you talking about? 😄

I have no idea... can't understand what you wrote.

**Comment by earlSt1** [comment]
Ohhh i see what you're talking about now. My module doesn't overwrite any
existing rendering code for folders like that. That could be done in
another module however ....

I'll add that to my module ideas list :)

**Comment by geoidesic** [comment]
Please remove the image in your reply from GitHub history? 
I tested this on my local installation, which is old from when I was experimenting with modules and the image includes reference to a module I was testing which I've since realised is viewed unfavourably.

**Comment by scooper4711** [comment]
Please widen this to text and folder colors when importing journals, scenes and actors.
i.e. I’d like scene packer to re-create the folder structure and also the folder colors - even when using Compendium Folders.

**Comment by earlSt1** [comment]
Hi, the module already allows you to import folder colors, Text colors are
not in core but i can look at including this soon.

I'm not sure how Scene Packer works exactly, it may require an update by
the module author to use the new folder API i've introduced.

**Comment by scooper4711** [comment]
Nevermind me. I thought I was commenting on an issue in Scene Packer. Not sure I know how I got here...*looks for car keys*
